# Generated by Django 5.2.17 on 2026-10-02 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=40)),
                ('provider_id', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(default='sending', max_length=20)),
                ('callback_digest', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SmsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('provider_id', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'permissions': [('send_messages', 'Queue and retry customer SMS')]},
        ),
        migrations.AddField(
            model_name='access',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='encoding',
            field=models.CharField(default='gsm7', max_length=12),
        ),
        migrations.AddField(
            model_name='message',
            name='last_error',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='message',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='queued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='segments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='message',
            name='source_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('branch', 'source_key'), name='unique_message_source'),
        ),
        migrations.AddField(
            model_name='smsattempt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='core.message'),
        ),
        migrations.AddField(
            model_name='smsevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.smsattempt'),
        ),
        migrations.AddConstraint(
            model_name='smsattempt',
            constraint=models.UniqueConstraint(fields=('message', 'number'), name='unique_sms_attempt'),
        ),
    ]
