import decimal
import uuid

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


def seed_ghana_payroll_2026(apps, schema_editor):
    PayrollRule = apps.get_model("core", "PayrollRule")
    PayrollRule.objects.get_or_create(
        code="GH-PAYROLL",
        effective_from="2026-09-01",
        defaults={
            "name": "Ghana payroll rules — September 2026",
            "resident_bands": [
                {"amount": "588.00", "rate": "0"},
                {"amount": "80.00", "rate": "5"},
                {"amount": "100.00", "rate": "10"},
                {"amount": "2900.00", "rate": "17.5"},
                {"amount": "16000.00", "rate": "25"},
                {"amount": "30332.00", "rate": "30"},
                {"amount": None, "rate": "35"},
            ],
            "employee_ssnit_rate": decimal.Decimal("5.5"),
            "employer_pension_rate": decimal.Decimal("13"),
            "first_tier_rate": decimal.Decimal("13.5"),
            "tier2_rate": decimal.Decimal("5"),
            "min_insurable_earnings": decimal.Decimal("587.80"),
            "max_insurable_earnings": decimal.Decimal("69000.00"),
            "nonresident_rate": decimal.Decimal("25"),
            "casual_rate": decimal.Decimal("5"),
            "bonus_rate": decimal.Decimal("5"),
            "bonus_limit_percent": decimal.Decimal("15"),
            "junior_overtime_rate": decimal.Decimal("5"),
            "junior_overtime_excess_rate": decimal.Decimal("10"),
            "junior_overtime_basic_limit": decimal.Decimal("18000"),
            "notes": "Seeded from current Ghana 2026 payroll settings. Review official GRA and SSNIT notices before changing effective versions.",
            "active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0017_direct_sms_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="expense_category",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.CreateModel(
            name="PayrollRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(default="GH-PAYROLL", max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("resident_bands", models.JSONField(default=list)),
                ("employee_ssnit_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("5.5"), max_digits=7)),
                ("employer_pension_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("13"), max_digits=7)),
                ("first_tier_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("13.5"), max_digits=7)),
                ("tier2_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("5"), max_digits=7)),
                ("min_insurable_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("max_insurable_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("nonresident_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("25"), max_digits=7)),
                ("casual_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("5"), max_digits=7)),
                ("bonus_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("5"), max_digits=7)),
                ("bonus_limit_percent", models.DecimalField(decimal_places=4, default=decimal.Decimal("15"), max_digits=7)),
                ("junior_overtime_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("5"), max_digits=7)),
                ("junior_overtime_excess_rate", models.DecimalField(decimal_places=4, default=decimal.Decimal("10"), max_digits=7)),
                ("junior_overtime_basic_limit", models.DecimalField(decimal_places=2, default=decimal.Decimal("18000"), max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-effective_from", "-pk"]},
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_code", models.CharField(max_length=30, unique=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("other_names", models.CharField(blank=True, max_length=120)),
                ("preferred_name", models.CharField(blank=True, max_length=80)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(default="Ghanaian", max_length=60)),
                ("marital_status", models.CharField(blank=True, max_length=30)),
                ("phone", models.CharField(max_length=30)),
                ("alternate_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("residential_address", models.TextField(blank=True)),
                ("digital_address", models.CharField(blank=True, max_length=80)),
                ("ghana_card_number", models.CharField(blank=True, max_length=40)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("ssnit_number", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(max_length=120)),
                ("employment_type", models.CharField(choices=[("permanent", "Permanent"), ("contract", "Contract"), ("casual", "Casual"), ("intern", "Intern / trainee"), ("probation", "Probation")], default="permanent", max_length=20)),
                ("status", models.CharField(choices=[("active", "Active"), ("leave", "On leave"), ("suspended", "Suspended"), ("exited", "Exited")], default="active", max_length=20)),
                ("hire_date", models.DateField()),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                ("salary_basis", models.CharField(choices=[("monthly", "Monthly"), ("daily", "Daily"), ("hourly", "Hourly")], default="monthly", max_length=12)),
                ("base_salary", models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("recurring_allowance", models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("ssnit_enabled", models.BooleanField(default=True)),
                ("tax_mode", models.CharField(choices=[("resident", "Resident PAYE"), ("nonresident", "Non-resident"), ("casual", "Casual worker"), ("exempt", "Exempt")], default="resident", max_length=14)),
                ("junior_staff", models.BooleanField(default=False)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=120)),
                ("bank_account_number", models.CharField(blank=True, max_length=80)),
                ("momo_network", models.CharField(blank=True, max_length=40)),
                ("momo_number", models.CharField(blank=True, max_length=30)),
                ("emergency_name", models.CharField(blank=True, max_length=120)),
                ("emergency_relationship", models.CharField(blank=True, max_length=60)),
                ("emergency_phone", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("card_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workers", to="core.branch")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="worker_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["last_name", "first_name", "employee_code"]},
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("prepared", "Prepared for review"), ("approved", "Approved"), ("locked", "Locked for payment"), ("reconciled", "Reconciled")], default="draft", max_length=16)),
                ("note", models.TextField(blank=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_periods", to="core.branch")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("prepared_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("rule", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.payrollrule")),
            ],
            options={"ordering": ["-year", "-month", "-pk"]},
        ),
        migrations.CreateModel(
            name="WorkerDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("photo", "Profile photo"), ("identity", "Identity document"), ("contract", "Employment contract"), ("certificate", "Certificate / qualification"), ("tax", "Tax document"), ("ssnit", "SSNIT document"), ("medical", "Medical / welfare"), ("disciplinary", "Disciplinary record"), ("other", "Other")], default="other", max_length=20)),
                ("title", models.CharField(max_length=180)),
                ("document_type", models.CharField(blank=True, max_length=100)),
                ("document_number", models.CharField(blank=True, max_length=120)),
                ("original_filename", models.CharField(max_length=220)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("file_data", models.BinaryField()),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="core.worker")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("basic_salary", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("allowances", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("bonus", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("overtime", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("other_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("pretax_relief", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("other_deductions", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("gross_pay", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("ssnit_employee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("employer_pension", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("first_tier_remittance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tier2_contribution", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("chargeable_income", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paye_tax", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("bonus_tax", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("overtime_tax", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("net_pay", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("calculation_snapshot", models.JSONField(default=dict)),
                ("validation_flags", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="core.payrollperiod")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_entries", to="core.worker")),
            ],
            options={"ordering": ["worker__last_name", "worker__first_name", "worker__employee_code"]},
        ),
        migrations.CreateModel(
            name="PayrollPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))])),
                ("method", models.CharField(choices=[("cash", "Cash"), ("momo", "MoMo"), ("bank", "Bank"), ("card", "Card")], max_length=12)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="core.payrollentry")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="worker", index=models.Index(fields=["branch", "status", "department"], name="worker_branch_status_idx")),
        migrations.AddIndex(model_name="worker", index=models.Index(fields=["employee_code"], name="worker_employee_code_idx")),
        migrations.AddConstraint(model_name="worker", constraint=models.CheckConstraint(condition=models.Q(("base_salary__gte", 0), ("recurring_allowance__gte", 0)), name="worker_compensation_nonnegative")),
        migrations.AddIndex(model_name="workerdocument", index=models.Index(fields=["worker", "category", "is_current"], name="worker_doc_current_idx")),
        migrations.AddConstraint(model_name="payrollrule", constraint=models.UniqueConstraint(fields=("code", "effective_from"), name="payroll_rule_effective_version")),
        migrations.AddIndex(model_name="payrollperiod", index=models.Index(fields=["branch", "year", "month", "status"], name="payroll_period_lookup_idx")),
        migrations.AddConstraint(model_name="payrollperiod", constraint=models.UniqueConstraint(fields=("branch", "year", "month"), name="one_payroll_period_per_branch_month")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.UniqueConstraint(fields=("period", "worker"), name="one_payroll_entry_per_worker_period")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.CheckConstraint(condition=models.Q(("paid_amount__gte", 0)), name="payroll_paid_nonnegative")),
        migrations.RunPython(seed_ghana_payroll_2026, migrations.RunPython.noop),
    ]
