# Generated for KOFAD online market and fulfilment.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0022_worker_identity_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("password_hash", models.CharField(max_length=160)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["full_name", "phone"]},
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("eta_text", models.CharField(blank=True, default="", max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="MarketListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=False)),
                ("featured", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price_source", models.CharField(choices=[("retail_unit", "Retail price · single unit"), ("retail_pack", "Retail price · full pack"), ("wholesale_unit", "Wholesale price · single unit"), ("wholesale_pack", "Wholesale price · full pack")], default="retail_unit", max_length=24)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("image_data", models.BinaryField(blank=True, editable=False, null=True)),
                ("image_thumb", models.BinaryField(blank=True, editable=False, null=True)),
                ("image_mime", models.CharField(blank=True, default="image/webp", max_length=40)),
                ("image_name", models.CharField(blank=True, max_length=180)),
                ("image_updated_at", models.DateTimeField(blank=True, null=True)),
                ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="market_listing", to="core.product")),
            ],
            options={"ordering": ["sort_order", "product__name"]},
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(default="Delivery address", max_length=60)),
                ("recipient_name", models.CharField(max_length=140)),
                ("phone", models.CharField(max_length=20)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("town", models.CharField(max_length=120)),
                ("address_line", models.TextField()),
                ("landmark", models.CharField(blank=True, max_length=220)),
                ("ghana_post_gps", models.CharField(blank=True, max_length=40)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="marketplace.customeraccount")),
            ],
            options={"ordering": ["-is_default", "-created_at"]},
        ),
        migrations.CreateModel(
            name="OnlineOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("public_reference", models.CharField(max_length=32, unique=True)),
                ("status", models.CharField(choices=[("awaiting_payment", "Awaiting payment"), ("paid", "Paid"), ("confirmed", "Confirmed"), ("preparing", "Preparing"), ("ready_pickup", "Ready for pickup"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("picked_up", "Picked up"), ("cancelled", "Cancelled"), ("refund_pending", "Refund pending"), ("refunded", "Refunded")], default="awaiting_payment", max_length=24)),
                ("payment_status", models.CharField(choices=[("unpaid", "Unpaid"), ("initializing", "Initializing"), ("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("refunded", "Refunded")], default="unpaid", max_length=16)),
                ("ledger_status", models.CharField(choices=[("pending", "Pending"), ("posted", "Posted"), ("attention", "Needs attention")], default="pending", max_length=16)),
                ("fulfilment", models.CharField(choices=[("delivery", "Delivery"), ("pickup", "Pickup")], default="delivery", max_length=12)),
                ("recipient_name", models.CharField(max_length=140)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("town", models.CharField(blank=True, max_length=120)),
                ("address_line", models.TextField(blank=True)),
                ("landmark", models.CharField(blank=True, max_length=220)),
                ("ghana_post_gps", models.CharField(blank=True, max_length=40)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("customer_note", models.TextField(blank=True)),
                ("staff_note", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("delivery_fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_channel", models.CharField(blank=True, max_length=40)),
                ("delivery_agent_name", models.CharField(blank=True, max_length=140)),
                ("delivery_agent_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="online_orders", to="core.branch")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="marketplace.customeraccount")),
                ("delivery_zone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="marketplace.deliveryzone")),
                ("party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="online_orders", to="core.party")),
                ("sale_document", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="online_order", to="core.document")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["branch", "status", "created_at"], name="market_order_status_idx"),
                    models.Index(fields=["customer", "created_at"], name="market_customer_order_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnlineOrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=180)),
                ("sku", models.CharField(max_length=40)),
                ("mode", models.CharField(max_length=40)),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("factor", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="marketplace.marketlisting")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="marketplace.onlineorder")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product")),
            ],
            options={"ordering": ["pk"]},
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("units", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("expires_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="marketplace.onlineorder")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.product")),
            ],
            options={
                "indexes": [models.Index(fields=["branch", "product", "active", "expires_at"], name="market_stock_reservation_idx")],
                "constraints": [models.UniqueConstraint(fields=("order", "product"), name="one_market_reservation_per_product")],
            },
        ),
        migrations.CreateModel(
            name="MarketPaymentAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="paystack", max_length=24)),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("status", models.CharField(default="initialized", max_length=24)),
                ("access_code", models.CharField(blank=True, max_length=120)),
                ("authorization_url", models.URLField(blank=True)),
                ("provider_message", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_attempts", to="marketplace.onlineorder")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=140)),
                ("note", models.TextField(blank=True)),
                ("customer_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="marketplace.onlineorder")),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_name", models.CharField(blank=True, max_length=140)),
                ("public_phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(default="Customer enquiry", max_length=180)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="market_conversations", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="marketplace.customeraccount")),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="marketplace.onlineorder")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_type", models.CharField(choices=[("visitor", "Visitor"), ("customer", "Customer"), ("staff", "Staff")], max_length=12)),
                ("body", models.TextField()),
                ("read_by_staff", models.BooleanField(default=False)),
                ("read_by_customer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="marketplace.conversation")),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="OtpThrottle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=20)),
                ("purpose", models.CharField(choices=[("register", "Register"), ("reset", "Reset password"), ("login", "Customer login")], max_length=12)),
                ("send_count", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("phone", "purpose"), name="one_market_otp_throttle")]},
        ),
    ]
