from . import whatsapp_bot_views
from django.conf import settings
from django.urls import path
from . import views as v
from . import account as accounts
from . import count_views
from . import admin_views
from . import export_views
from . import maintenance_views
from . import accounting_views, approval_views, creditor_views, payroll_views, whatsapp_views, workforce_views
from .sms.views import callback, delivery_callback as v_sms_delivery_callback
urlpatterns = [
    path("settings/whatsapp-bot/", whatsapp_bot_views.dashboard, name="whatsapp_bot_dashboard"),
    path("account/", accounts.account, name="account"),
    path("approvals/", approval_views.approval_center, name="approval_center"),
    path("approvals/action/", approval_views.approval_action, name="approval_action"),
    path("api/approvals/summary/", approval_views.approval_summary, name="approval_summary"),
    path("settings/return-privileges/", approval_views.return_privileges, name="return_privileges"),
    path("forgot-password/", accounts.forgot_password, name="forgot_password"),
    path("forgot-password/code/", accounts.reset_password, name="reset_password"),
    path("stock-counts/", count_views.index, name="stock_counts"),
    path("stock-counts/<uuid:pk>/", count_views.detail, name="stock_count"),
    path("stock-counts/<uuid:pk>/export/<str:format>/", count_views.export_count, name="stock_count_export"),
    path("sms/callback/<uuid:attempt_id>/", callback, name="sms_callback"),
    path("sms/delivery/", v_sms_delivery_callback, name="sms_delivery_callback"),
    path("whatsapp/webhook/", whatsapp_views.webhook, name="whatsapp_webhook"),
    path("message-templates/", v.message_templates, name="message_templates"),
    path("account/password/", v.password_change, name="password_change"),
    path("search/", v.search, name="search"),
    path("health/", v.health, name="health"), path(settings.STAFF_LOGIN_SLUG + "/", v.login_view, name="login"),
    path("logout/", v.logout_view, name="logout"), path("session/state/", v.staff_session_state, name="staff_session_state"), path("mfa/", v.mfa, name="mfa"),
    path("branch/", v.switch_branch, name="switch_branch"), path("workspace/", v.dashboard, name="dashboard"),
    path("sales/new/", v.pos, name="pos"), path("purchasing/", v.purchasing, name="purchasing"),
    path("api/trades/", v.complete_trade),
    path("api/pos/paystack-momo/<str:reference>/otp/", v.pos_paystack_momo_otp, name="pos_paystack_momo_otp"),
    path("api/pos/paystack-momo/start/", v.pos_paystack_momo_start, name="pos_paystack_momo_start"),
    path("api/pos/paystack-momo/<str:reference>/status/", v.pos_paystack_momo_status, name="pos_paystack_momo_status"),
    path("api/documents/<uuid:pk>/send-sms/", v.send_transaction_message_api, name="send_transaction_message_api"),
    path("api/customers/", v.customer_search, name="customer_search"),
    path("api/suppliers/", creditor_views.supplier_search, name="supplier_search"), path("api/held/", v.hold),
    path("api/held/<int:pk>/", v.held),
    path("documents/", v.documents, name="documents"), path("documents/<uuid:pk>/", v.document, name="document"),
    path("documents/<uuid:pk>/pdf/<str:format>/", v.document_pdf, name="document_pdf"),
    path("inventory/", v.inventory, name="inventory"), path("products/new/", v.product_edit, name="product_new"),
    path("products/<int:pk>/", v.product_edit, name="product_edit"),
    path("parties/", v.parties, name="parties"), path("parties/new/", v.party_edit, name="party_new"),
    path("parties/<int:pk>/", v.party_edit, name="party_edit"), path("customers/<int:pk>/", v.customer_profile, name="customer_profile"),
    path("parties/<int:pk>/statement/", v.statement, name="statement"),
    path("parties/<int:pk>/statement/export/<str:format>/", export_views.statement_download, name="statement_export"),
    path("corrections/", v.corrections, name="corrections"),
    path("debts/", v.debts, name="debts"),
    path("finance/", v.finance, name="finance"),
    path("accounting/", accounting_views.accounting, name="accounting"),
    path("creditors/", creditor_views.creditors, name="creditors"),
    path("creditors/export/<str:format>/", creditor_views.creditors_export, name="creditors_export"),
    path("creditors/<int:pk>/statement/<str:format>/", creditor_views.creditor_statement_export, name="creditor_statement_export"),
    path("accounting/export/<str:format>/", accounting_views.accounting_export, name="accounting_export"),
    path("verify/worker/<uuid:token>/", workforce_views.worker_card_verify, name="worker_card_verify"),
    path("workers/", workforce_views.workers, name="workers"),
    path("workers/new/", workforce_views.worker_edit, name="worker_new"),
    path("workers/<int:pk>/edit/", workforce_views.worker_edit, name="worker_edit"),
    path("workers/<int:pk>/", workforce_views.worker_profile, name="worker_profile"),
    path("workers/<int:pk>/documents/", workforce_views.worker_document_upload, name="worker_document_upload"),
    path("workers/<int:pk>/documents/<int:document_id>/", workforce_views.worker_document_download, name="worker_document_download"),
    path("workers/<int:pk>/profile.pdf", workforce_views.worker_profile_pdf, name="worker_profile_pdf"),
    path("workers/<int:pk>/id-card.pdf", workforce_views.worker_id_card, name="worker_id_card"),
    path("workers/<int:pk>/id-card-print-sheet.pdf", workforce_views.worker_id_card_sheet, name="worker_id_card_sheet"),
    path("workers/export/<str:format>/", workforce_views.workers_export, name="workers_export"),
    path("payroll/", payroll_views.payroll, name="payroll"),
    path("payroll/rules/", payroll_views.payroll_rules, name="payroll_rules"),
    path("payroll/<int:pk>/", payroll_views.payroll_period, name="payroll_period"),
    path("payroll/<int:pk>/action/", payroll_views.payroll_action, name="payroll_action"),
    path("payroll/<int:pk>/entries/<int:entry_id>/", payroll_views.payroll_entry_update, name="payroll_entry_update"),
    path("payroll/<int:pk>/entries/<int:entry_id>/payment/", payroll_views.payroll_payment, name="payroll_payment"),
    path("payroll/<int:pk>/export/<str:format>/", payroll_views.payroll_export, name="payroll_export"),
    path("payroll/<int:pk>/payslip/<int:entry_id>/<str:format>/", payroll_views.payslip, name="payslip"),
    path("returns/", v.returns, name="returns"),
    path("supplier-returns/", v.supplier_returns, name="supplier_returns"),
    path("quarantine/", v.quarantine, name="quarantine"),
    path("operations/", v.operations, name="operations"), path("closings/", v.closings, name="closings"),
    path("reports/", v.reports, name="reports"), path("reports/export/<str:format>/", v.export_report, name="export"),
    path("audit/", v.audit_log, name="audit"),
    path("administration/", admin_views.administration, name="administration"),
    path("administration/users/", admin_views.users, name="admin_users"),
    path("administration/users/new/", admin_views.user_edit, name="admin_user_new"),
    path("administration/users/<int:pk>/", admin_views.user_edit, name="admin_user_edit"),
    path("administration/roles/", admin_views.roles, name="admin_roles"),
    path("administration/roles/new/", admin_views.role_edit, name="admin_role_new"),
    path("administration/roles/<int:pk>/", admin_views.role_edit, name="admin_role_edit"),
    path("settings/", admin_views.settings_center, name="settings"),
    path("settings/company/", v.settings_view, name="company_settings"),
    path("settings/location/", v.location_settings, name="location_settings"),
    path("settings/debt/", v.debt_settings, name="debt_settings"),
    path("settings/communications/", v.communication_settings, name="communication_settings"),
    path("settings/sales/", v.sales_policy_settings, name="sales_policy_settings"),
    path("settings/payments/", v.payment_policy_settings, name="payment_policy_settings"),
    path("settings/finance/", v.finance_policy_settings, name="finance_policy_settings"),
    path("settings/receipts/", v.receipt_policy_settings, name="receipt_policy_settings"),
    path("settings/backup/", maintenance_views.backup_restore, name="backup_restore"),
    path("settings/backup/download/", maintenance_views.download_backup, name="backup_download"),
    path("settings/backup/status/", maintenance_views.backup_status, name="backup_status"),
    path("exports/", export_views.export_center, name="export_center"),
    path("exports/download/<str:format>/", export_views.download, name="export_download"),
    path("communications/", v.communications, name="communications"),
    path("api/communications/status/", v.communication_status, name="communication_status"),
]
