from django.urls import path
from . import views as v
from . import account as accounts
from . import count_views
from . import admin_views
from . import export_views
from . import maintenance_views
from .sms.views import callback, delivery_callback as v_sms_delivery_callback
urlpatterns = [
    path("account/", accounts.account, name="account"),
    path("forgot-password/", accounts.forgot_password, name="forgot_password"),
    path("forgot-password/code/", accounts.reset_password, name="reset_password"),
    path("stock-counts/", count_views.index, name="stock_counts"),
    path("stock-counts/<uuid:pk>/", count_views.detail, name="stock_count"),
    path("sms/callback/<uuid:attempt_id>/", callback, name="sms_callback"),
    path("sms/delivery/", v_sms_delivery_callback, name="sms_delivery_callback"),
    path("message-templates/", v.message_templates, name="message_templates"),
    path("account/password/", v.password_change, name="password_change"),
    path("search/", v.search, name="search"),
    path("health/", v.health, name="health"), path("login/", v.login_view, name="login"),
    path("logout/", v.logout_view, name="logout"), path("mfa/", v.mfa, name="mfa"),
    path("branch/", v.switch_branch, name="switch_branch"), path("", v.dashboard, name="dashboard"),
    path("sales/new/", v.pos, name="pos"), path("purchasing/", v.purchasing, name="purchasing"),
    path("api/trades/", v.complete_trade),
    path("api/documents/<uuid:pk>/send-sms/", v.send_transaction_message_api, name="send_transaction_message_api"),
    path("api/customers/", v.customer_search, name="customer_search"), path("api/held/", v.hold),
    path("api/held/<int:pk>/", v.held),
    path("documents/", v.documents, name="documents"), path("documents/<uuid:pk>/", v.document, name="document"),
    path("documents/<uuid:pk>/pdf/<str:format>/", v.document_pdf, name="document_pdf"),
    path("inventory/", v.inventory, name="inventory"), path("products/new/", v.product_edit, name="product_new"),
    path("products/<int:pk>/", v.product_edit, name="product_edit"),
    path("parties/", v.parties, name="parties"), path("parties/new/", v.party_edit, name="party_new"),
    path("parties/<int:pk>/", v.party_edit, name="party_edit"), path("customers/<int:pk>/", v.customer_profile, name="customer_profile"),
    path("parties/<int:pk>/statement/", v.statement, name="statement"),
    path("parties/<int:pk>/statement/export/<str:format>/", export_views.statement_download, name="statement_export"),
    path("corrections/", v.corrections, name="corrections"),
    path("debts/", v.debts, name="debts"),
    path("finance/", v.finance, name="finance"), path("returns/", v.returns, name="returns"),
    path("supplier-returns/", v.supplier_returns, name="supplier_returns"),
    path("quarantine/", v.quarantine, name="quarantine"),
    path("operations/", v.operations, name="operations"), path("closings/", v.closings, name="closings"),
    path("reports/", v.reports, name="reports"), path("reports/export/<str:format>/", v.export_report, name="export"),
    path("audit/", v.audit_log, name="audit"),
    path("administration/", admin_views.administration, name="administration"),
    path("administration/users/", admin_views.users, name="admin_users"),
    path("administration/users/new/", admin_views.user_edit, name="admin_user_new"),
    path("administration/users/<int:pk>/", admin_views.user_edit, name="admin_user_edit"),
    path("administration/roles/", admin_views.roles, name="admin_roles"),
    path("administration/roles/new/", admin_views.role_edit, name="admin_role_new"),
    path("administration/roles/<int:pk>/", admin_views.role_edit, name="admin_role_edit"),
    path("settings/", admin_views.settings_center, name="settings"),
    path("settings/company/", v.settings_view, name="company_settings"),
    path("settings/location/", v.location_settings, name="location_settings"),
    path("settings/debt/", v.debt_settings, name="debt_settings"),
    path("settings/communications/", v.communication_settings, name="communication_settings"),
    path("settings/sales/", v.sales_policy_settings, name="sales_policy_settings"),
    path("settings/payments/", v.payment_policy_settings, name="payment_policy_settings"),
    path("settings/finance/", v.finance_policy_settings, name="finance_policy_settings"),
    path("settings/receipts/", v.receipt_policy_settings, name="receipt_policy_settings"),
    path("settings/backup/", maintenance_views.backup_restore, name="backup_restore"),
    path("settings/backup/download/", maintenance_views.download_backup, name="backup_download"),
    path("exports/", export_views.export_center, name="export_center"),
    path("exports/download/<str:format>/", export_views.download, name="export_download"),
    path("communications/", v.communications, name="communications"),
]
